#!/usr/bin/env bash

FIX_KEYWORDS=('mark.only' 'TODO' 'DEBUG' 'debug_shell' 'breakpoint')

for keyword in ${FIX_KEYWORDS[@]}; do
  ag $keyword .
done

dev/pre-release/lint-all
dev/start-tests-all --flags pre-release $@

