ARG ARG_REQUIRED_IMAGE
FROM $ARG_REQUIRED_IMAGE

ARG ARG_USER

ENV PYTEST_CLI_CMD="bt-dualboot" PATH="/home/$ARG_USER/.local/bin:$PATH"

COPY . /prj/

RUN sudo chown -R $ARG_USER /prj && cd /prj \
  && pip install devpi-server devpi-client \
  && ./dev/bootstrap

RUN cd /prj \
  && /docker/devpi-bootstrap \
  # Setup and publish pypi package, then pip install it
  && poetry config repositories.test http://localhost:3141/root/test \
  && poetry publish --build -r test -u root -p topsecret \
  && sudo pip install -i http://localhost:3141/root/test bt-dualboot \
  && /docker/devpi-stop \
  # avoid false-positive tests
  && rm ./bt-dualboot \
  # patch snapshot expectations
  && find ./tests_integration/cli/env_single_windows/snapshots -name output -exec sed -i 's/\/src\/bt-dualboot/bt-dualboot/g' {} \;


